<h2 class="heading-two">Arbor Service 
    <span>Aanplanten van bomen of leibomen</span>
</h2>
<p>Het correct aanplanten van een boom begint voor ons bij de juiste keuze van de boomsoort. Hierin kunnen wij u bijstaan dankzij onze grote kennis van boomsoorten. Om de juiste boomsoort te kiezen moet er o.a. rekening gehouden worden met de standplaatsgeschiktheid en het gewenste eindbeeld, dit zijn de twee belangrijkste factoren.</p>

<p>Als u uw keuze heeft gemaakt, kunnen we overgaan tot het aanplanten van de boom. Het is belangrijk dat het aanplanten van de boom op een professionele manier gebeurd. Te diep aanplanten is één van de hoofdoorzaken van sterfte binnen het eerste jaar na het aanplanten van de boom. Correct water geven en begeleidingssnoei zorgen ervoor dat uw boom snel een volwassen staat kan bereiken. Om geen juridische problemen te krijgen is het ook zeer belangrijk dat de boom op een reglementaire wijze wordt aangepland.</p>

<p>Voor het juiste advies en een goede aanplanting staan wij voor u klaar.</p>
