<h2 class="heading-two">Arbor Service <span>Advies</span></h2>
<p>Als (toekomstige) boomeigenaar zit u vaak met veel vragen, wij zijn er dan als boomadviseur om u een antwoord te geven op al uw vragen. Is uw boom nog veilig, gezond en stabiel? Wat is de waarde van uw boom? Advies i.v.m. de keuze en de plaatsing van een boom. Voor al uw vragen staan wij paraat met het geschikte onderzoek: bodemonderzoek, gezondheidsonderzoek, waardebepaling (belangrijk indien uw boom beschadigd raakt door derden), plantadvies, stabiliteitsonderzoek, juridisch advies, … Wij kunnen u een duidelijke uitleg geven, waarna u zelf kan beslissen wat u verder doet.</p>

<p>Contacteer ons bij vragen rond uw boombestand.</p>
