<h2 class="heading-two">Arbor Service <span>Boomveiligheids- inspecties</span></h2>
<p>Dankzij een grondig veiligheidsonderzoek van uw boom kunnen wij bepalen of uw boom veilig en stabiel is en wat de eventuele reden is voor zijn slechte groei.</p>

<p>We starten ons onderzoek altijd met een algemene inspectie (VTA). Nadien is het mogelijk dat het nodig is om meerdere onderzoeken uit te voeren. Dit kunnen veel verschillende soorten onderzoeken zijn, afhankelijk van de noden van uw boom: verschillende bodemonderzoeken, stabiliteitsonderzoek, wortelonderzoek en het inspecteren van eventuele holtes en mechanische gebreken en het onderzoeken van aantastingen (zwammen en andere schimmelaantastingen).</p>

<p>Dankzij deze onderzoeken krijgt u een duidelijk beeld over de gezondheid van uw boom en van de bodemgesteldheid.</p>

