<h2 class="heading-two">Arbor Service 
    <span>Inventarisatie en beheer planning van boombestanden</span>
</h2>

<p>Om het arbeids- en onderhoudsproces te versnellen en efficiënter te kunnen werken is het een grote hulp om een inventarisatie en een beheersplanning op te stellen van uw bomenbestand.</p>

<p>Wij maken voor u een duidelijk overzicht van uw bomenbestand. Dit doen we door alles schematisch in kaart te brengen, geografisch in te geven, de gezondheidstoestand te bepalen en al uw bomen te nummeren en te labelen.</p>

<p>Hierdoor zal u op termijn veel tijd en arbeid uitsparen.</p>
