<h2 class="heading-two">Arbor Service 
    <span>Kroon- en kluitverankering</span>
</h2>

<p>Indien er bij uw boom kans is op uitbreken of uitscheuren van kroondelen, is het niet altijd nodig om deze boom te vellen. We kunnen hier een verankering plaatsen om zo het uitbreken of uitscheuren te voorkomen.</p>

<p>Het is natuurlijk ook mogelijk dat de wortelkluit onstabiel is geworden. Dan kunnen we kluitverankering toepassen om de boom meer stabiliteit te geven.</p>

<p>We kunnen ook preventief een dynamische kluitverankering plaatsen. Kroon- en kluitverankering is een goedkope en toch duurzame oplossing om ervoor te zorgen dat uw boom nog vele jaren kan verder groeien, zonder een gevaar te zijn voor zijn omgeving.</p>
