<h2 class="heading-two">Arbor Service 
    <span>Standplaats verbetering</span>
</h2>
<p>De standplaats kan men verbeteren op verschillende manieren. Dit kan o.a. door het oplossen van de compactering van de grond door middel van ploffen waarbij barsten in de grond worden gemaakt. Hierdoor kan er opnieuw zuurstof naar de wortels. De compactering kan veroorzaakt zijn door machines die over en rondom het wortelgestel rijden. Een andere manier is door de kwaliteit van de grond rondom de boom te verbeteren. Door voedingstoffen aan te brengen aan de standplaats van de boom.</p>

<p>Indien u ziet dat de conditie van uw boom achteruitgaat, twijfel dan niet en neem onmiddellijk contact op met arbor-service.</p>
