<h2 class="heading-two">Arbor Service 
    <span>Tuinwerken</span>
</h2>

<p><strong>Te koop/huur</strong><br />
    Wil u een huis verkopen, maar is de tuin verwaarloosd? Dan heeft dit een negatieve invloed op de verkoop. Een goed verzorgde tuin is vaak de eyecatcher van een woning, dit kan potentiële kopers over de streep trekken.<br />
    Wij kunnen ervoor zorgen dat de meest verwaarloosde tuinen er weer aantrekkelijk uitzien. Dit zal de vraagprijs en de verkoop ten goede komen.</p>

<p><strong>Algemeen</strong><br />
    Kan u ook zo genieten van lekker ontspannen in uw tuin te zitten, maar heeft u geen zin om hier uren werk in te steken? Dan kan u bij ons terecht. Wij zorgen ervoor dat uw tuin er steeds verzorgd uitziet. Zo kan u elk moment van het jaar genieten van een prachtige tuin.<br />
    Wij kunnen u natuurlijk ook helpen bij taken die te moeilijk worden om zelf uit te voeren.</p>

<p><strong>Snoeiwerken</strong><br />
    Een tuin spreekt nog meer aan met mooi verzorgde hagen. Dit is echter niet altijd een makkelijke opdracht. Weet u zich geen raad met uw hagen of heesters, heeft u hulp nodig omdat de inspanning fysiek te zwaar is. Schakel dan onze hulp in!</p>

<p><strong>Gazon</strong><br />
    Is uw gazon toe aan vernieuwing, dan kan u bij ons terecht voor de heraanleg van uw gazon. Dit kan op twee verschillende manieren. We kunnen gras inzaaien of graszoden aanleggen. Het voordeel van graszoden is dat u onmiddellijk resultaat ziet Graszoden aanleggen is echter wel duurder.<br />
    Wij staan ook klaar voor het onderhoud van uw gazon: onkruidbestrijding, bemesten, kalken, verluchten, kale plekken herstellen, controle op engerlingen en gras afrijden.</p>