<h2 class="heading-two">Arbor Service 
    <span>Uitgraven of frezen van stronken</span>
</h2>
<p>Wanneer een boom geveld is, blijft de stronk over. Het duurt vele jaren voor de stronk begint weg te rotten. Indien u de stronk dieper dan het grondniveau hebt laten inzagen en hierover gras hebt gezaaid, dan zal je keer op keer een verzakking krijgen. Sommige stronken veroorzaken ook nieuw hout(wortelopslag).</p>

<p>Daarom is het belangrijk om de hele stronk weg te halen. Of gewoon omdat u op dezelfde plaats een nieuwe boom of andere beplanting wilt plaatsen. Dit is ook belangrijk bij ziektes om de kans op verspreiding zo klein mogelijk te houden.</p>

<p>Wij staan ook klaar voor het afvoeren van freesresten, het aanvoeren van vruchtbare grond en het herinzaaien van uw gazon, aanplanten van bomen, struiken, planten, …<br />
ZEER BELANGRIJK: Controleer eerst of er waterleidingen, elektriciteitsdraden of rioleringsbuizen aanwezig zijn in de grond die gefreesd moet worden. Een plan hiervan kan handig zijn.</p>

