<h2 class="heading-two">Arbor Service 
    <span>Verplanten van bomen</span>
</h2>
<p>Het verplanten van bomen is geen makkelijke klus. Er is een grote kennis en ervaring nodig om dit tot een goed einde te brengen.</p>

<p>Voor we aan de verplanting van een boom beginnen, geven we u advies over de verschillende mogelijkheden en over de slaagkans van uw verplantingsproject. Voor een goede verplanting van een boom is veel voorbereidingswerk nodig. De omstandigheden (o.a.: de conditie van de boom, de standplaats, eventueel snoeien, …) bepalen de duur van de voorbereiding.</p>

<p>Na een goede voorbereiding kan het verplanten van de boom beginnen. De boom moet verankerd worden, voorzien worden van water, beluchting en bemesting.</p>



