<h2 class="heading-two">Arbor Service 
    <span>Ziekte- en plaagbestrijding</span>
</h2>
<p>De gezondheid van uw boom kan in gevaar komen als uw boom last heeft van ziektes en/of plagen. Er zijn verschillende soorten ziektes en plagen die uw boom kunnen aantasten, indien er niets aan gedaan wordt kan dit zelfs de dood betekenen voor uw boom.</p>

<p>Een grondige analyse, een passend advies en een goed bestrijdingsplan zijn noodzakelijk om over te gaan tot de uitvoering van de plaagbestrijding. Het is zeer belangrijk om er tijdig bij te zijn, zo kunnen veel problemen voorkomen worden.</p>

<p>Niet alle ziektes en plagen zijn onmiddellijk zichtbaar, laat daarom je boom tijdig controleren indien u ongewone dingen opmerkt zoals afstervende takken, bruine plekken op bladeren, gaten in de schors, … Ook bij de eikenprocessierups is het zeer belangrijk dat er tijdig wordt ingegrepen, wilt u zichzelf beschermen tegen overlast.</p>

<p>Doet u dit niet wordt het steeds erger en wordt behandelen veel moeilijker en duurder.</p>

<p>Mogelijke ziektes en plagen: kastanjemineermot, bladluizen, iepenspintkever, schimmels, bacteriën, virussen, …</p>

